### ISSUE TITLE
getting "WARN deprecated crypto@1.0.1" on install

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-blob-files#2]
```
$ npm install ssb-blob-files
```

Then I get

> npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

Is it correct? Can you just use inbuilt crypto? @mixmix

**Comment by dominictarr** [comment]
did someone do `npm install crypto`?

**Comment by mixmix** [comment]
Oh yes, I'll remove that, thanks for pointing out.
Didn't know that was a node core lib

**Comment by mixmix** [comment]
resolved and published

**Comment by mixmix** [comment]
p.s. who wrote the bulk of this, I want to attribute it.
I can go check out the blame in patchcore but I suspect a bunch of it came from you upstream @dominictarr in patchbay 6 ?

**Comment by dominictarr** [comment]
some bits of this has been copy-pasted from code I wrote, but lots doesn't look like my code. I suspect some was paul's. hard to tell, I don't recommend copy-pasting code, on that note.

**Comment by mixmix** [comment]
too late!
