### ISSUE TITLE
localising error messages

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-blob-files#3]
I would like to display the error message (with actual file size etc) in Patchwork, but the way that the error is given doesn't give access to the file size. What about adding an error code to the error node style? 

```js
var error = new Error('Some message')
error.code = 'ETOOBIG'
error.fileSize = fileSize
error.fileName = fileName
cb(error)
```

cc @mixmix

**Comment by mixmix** [comment]
yeah I think that's a great idea.
You can open a PR and just merge that if you like!

I'll go add this repo to ssbc org on npm so you can publish too

**Comment by mmckegg** [comment]
Cool, I'll do this sometime!
