### ISSUE TITLE
`{ stripExif: true }` doesn't seem to work

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-blob-files#6]
See: https://github.com/ssbc/patchwork/issues/1022

After looking at the code it looks like we're checking whether `opts.stripExif === 'true'`, which compares against the string literal rather than a boolean: https://github.com/ssbc/ssb-blob-files/blob/2292085dc731f3a88de53dca02a863c17789c0b8/async/image-process.js#L12

cc: @mixmix

**Comment by mixmix** [comment]
ooof ... nice catch @christianbundy !

And thanks for the speedy fix @arj03 . I'll build this into the next installer I make
